array: array.c
		gcc array.c -g -o array
2d_array: 2d_array.c
		gcc 2d_array.c -g -o 2d_array
dynamic_arr: dynamic_arr.c
		gcc dynamic_arr.c -g -o dynamic_arr
clean: dynamic_arr 2d_array array
		rm dynamic_arr
		rm 2d_array
		rm array
