honi: honi.c
		gcc honi.c -g -o honi
combination: combination.c
		gcc combination.c -g -o combination

fibonacci: fibonacci.c
		gcc fibonacci.c -g -o fibonacci

taylor: taylor.c
		gcc taylor.c -g -o taylor
clean: taylor fibonacci combination honi
		rm taylor
		rm fibonacci
		rm combination
		rm honi
