toematrix: toematrix.c
		gcc toematrix.c -g -o toematrix
tridiag: tridiag.c
		gcc tridiag.c -g -o tridiag
up: up_train.c
		gcc up_train.c -g -o up_train
low: low_train.c
		gcc low_train.c -g -o low_train
diag: diag_matrix.c
		gcc diag_matrix.c -g -o diag_matrix
clean:
		rm diag_matrix
