stack:
	gcc stack.c -g -o stack
linkedlist_stack:
	gcc linkedlist_stack.c -g -o linkedlist_stack
postfix:
	gcc postfix.c -g -o postfix
Evaulation-Postfix:
	gcc Evaulation-Postfix.c -g -o Evaulation-Postfix
clean:
	rm stack
	rm linkedlist_stack
	rm postfix
