Display_LL:
		gcc Display_LL.c -g -o Display_LL
Circular_LL:
		gcc Circular_LL.c -g -o Circular_LL
db_LL:
		gcc db_LL.c -g -o db_LL
db_cir_LL:
		gcc db_cir_LL.c -g -o db_cir_LL
Polynomial_LL:
		gcc -g -o Polynomial_LL Polynomial_LL.c -lm
clean:
		rm Display_LL
		rm Circular_LL
		rm db_LL
		rm db_cir_LL
