bubble:
		gcc Bubble.c -g -o bubble.out
insertion:
		gcc Insertion.c -g -o insert.out
selection:
		gcc Selection.c -g -o selection.out
quick:
		gcc Quick.c -g -o quick.out
merge:
		gcc Merge.c -g -o merge.out
count:
		gcc Count.c -g -o count.out
shell:
		gcc Shell.c -g -o shell.out
bucket:
		gcc Bucket.c -g -o bucket.out
radix:
		gcc Radix.c -g -o radix.out
radixlist:
		gcc Radix_linkedlist.c -g -o radixlist.out
clean:
	rm bubble.out
	rm bucket.out
	rm insert.out
	rm selection.out
	rm quick.out
	rm merge.out
	rm count.out
	rm shell.out
	rm radix.out
	rm radixlist.out
