bubble:
		gcc Bubble.c -g -o bubble.out
insertion:
		gcc Insertion.c -g -o insert.out
selection:
		gcc Selection.c -g -o selection.out
quick:
		gcc Quick.c -g -o quick.out
merge:
		gcc Merge.c -g -o merge.out
clean:
	rm bubble.out
	rm insert.out
	rm selection.out
	rm quick.out
	rm merge.out
